
POST http://localhost:5000/signup
Content-Type: application/json

{
  "fullName": "fn",
  "email":"fn@fn.com",
  "password": "fnfnfn",
  "password2": "fnfnfn",
  "country": "Country"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
  "email":"abc@abc.com",
  "password": "abcabc"
}

###